# File paths
gsw_params_path: "data/raw/gsw_params.csv"
nss_params_path: 'data/clean/nss_params.csv'

# User inputs
date_begin: '1987-01-31'
date_end:  '2011-12-31'
maturity_array: [1, 3, 6, 12, 24, 36, 48, 60, 72, 84, 96, 108, 120] # Months.
K: 5 # Number of factors.